# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: codens
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: forget-password
service: forget-password
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
functions:
  forget-password:
    handler: src/handler.main
    events:
      - http:
          path: /
          method: post
plugins:
  - serverless-offline